// Nerd Font icons over data.json (generated by build.ts from the release's
// glyphnames.json: `[name, code]` pairs by set): a grid inside, tiles are
// the glyphs, sections are the sets. Copy the glyph, its code point, its
// `nf-<set>-<name>` name or the CSS class. The last few picked lead the
// list in a "Recent" section (storage). A second grid lists the
// freedesktop icon names the SDK's `xdg()` knows, each with its glyph.
import { settings, storage, XDG_ICONS, type Action, type Detail, type Extension, type Item } from "@zcag/pal";
import data from "./data.json";

type Data = { version: string; sets: Record<string, [string, string][]> };
/** `[palettes.icons]`, default in pal.json. */
type PaletteSettings = { columns: number };

const RECENT_KEY = "recent";
const RECENT_MAX = 12;
const RECENT = "Recent";
/** md-font_awesome, the palette's own row. */
const ICON = "\u{f0151}";

/** The sets in the order the grid lists them, with the label the section shows. */
const SETS: Record<string, string> = {
  md: "Material Design", fa: "Font Awesome", cod: "Codicons", oct: "Octicons", dev: "Devicons", seti: "Seti", weather: "Weather", linux: "Font Logos", fae: "Font Awesome Extension",
  pl: "Powerline", ple: "Powerline Extra", pom: "Pomicons", iec: "IEC Power", custom: "Custom", extra: "Extra", indent: "Indent", indentation: "Indentation",
};

type Glyph = { id: string; set: string; name: string; code: string };
const { version, sets } = data as unknown as Data;
const glyphs: Glyph[] = Object.keys(SETS).concat(Object.keys(sets).filter((s) => !(s in SETS))).flatMap((set) => (sets[set] ?? []).map(([name, code]) => ({ id: `nf-${set}-${name}`, set, name, code })));
const byId = new Map(glyphs.map((g) => [g.id, g]));
const byCode = new Map(glyphs.map((g) => [g.code, g]));

const char = (g: Glyph) => String.fromCodePoint(parseInt(g.code, 16));
const codePoint = (code: string) => `U+${code.toUpperCase()}`;
const label = (set: string) => SETS[set] ?? set;

const ACTIONS: Action[] = [
  { id: "glyph", title: "Copy glyph" },
  { id: "codepoint", title: "Copy code point" },
  { id: "name", title: "Copy name" },
  { id: "class", title: "Copy CSS class" },
];

const item = (g: Glyph, section: string): Item => ({
  id: g.id,
  name: g.name.replace(/_/g, " "),
  // Eleven thousand rows cross the wire on every listing, so each carries the least: the set is the section, the code is in the subtitle.
  subtitle: codePoint(g.code),
  icon: char(g),
  keywords: [g.id],
  section,
  actions: ACTIONS,
});

async function recent(): Promise<string[]> {
  const ids = await storage.get<unknown>(RECENT_KEY);
  return Array.isArray(ids) ? ids.filter((id): id is string => typeof id === "string" && byId.has(id)) : [];
}
async function remember(id: string) {
  await storage.set(RECENT_KEY, [id, ...(await recent()).filter((x) => x !== id)].slice(0, RECENT_MAX));
}

/** No big glyph in the markdown: the pane's text is the UI font, and only the icon box uses the bundled symbols font. */
const detail = (g: Glyph): Detail => ({
  markdown: `**${g.name.replace(/_/g, " ")}**\n\n${label(g.set)} (${g.set}), Nerd Fonts ${version}`,
  metadata: [
    { label: "Name", value: g.id },
    { label: "Code point", value: codePoint(g.code) },
    { label: "CSS class", value: `nf ${g.id}` },
    { label: "Escape", value: `\\u{${g.code}}` },
  ],
});

// ---- freedesktop -----------------------------------------------------------

const XDG_ACTIONS: Action[] = [
  { id: "name", title: "Copy name" },
  { id: "glyph", title: "Copy glyph" },
  { id: "codepoint", title: "Copy code point" },
];
const xdgRows: Item[] = Object.entries(XDG_ICONS).map(([name, glyph]) => {
  const nf = byCode.get(glyph.codePointAt(0)!.toString(16).padStart(4, "0"));
  return { id: name, name, subtitle: nf?.id, icon: glyph, keywords: nf ? [nf.id] : [], actions: XDG_ACTIONS };
});

export default {
  palettes: {
    icons: {
      title: "Nerd Font icons",
      icon: ICON,
      view: "grid",
      // Palette meta is read once at load (see emoji).
      columns: settings.palette<PaletteSettings>("icons").columns,
      list: async () => {
        const used = await recent();
        return [...used.map((id) => item(byId.get(id)!, RECENT)), ...glyphs.filter((g) => !used.includes(g.id)).map((g) => item(g, label(g.set)))];
      },
      pick: async (id, action) => {
        const g = byId.get(id);
        if (!g) return { toast: { title: "Unknown glyph", message: id, style: "failure" } };
        await remember(id);
        switch (action) {
          case "codepoint": return { copy: codePoint(g.code) };
          case "name": return { copy: g.id };
          case "class": return { copy: `nf ${g.id}` };
          default: return { copy: char(g) };
        }
      },
      detail: (id) => { const g = byId.get(id); return g ? detail(g) : undefined; },
    },
    freedesktop: {
      title: "Freedesktop icon names",
      icon: ICON,
      view: "grid",
      columns: 10,
      list: () => xdgRows,
      pick: (id, action) => {
        const glyph = XDG_ICONS[id];
        if (!glyph) return { toast: { title: "Unknown icon name", message: id, style: "failure" } };
        switch (action) {
          case "glyph": return { copy: glyph };
          case "codepoint": return { copy: codePoint(glyph.codePointAt(0)!.toString(16).padStart(4, "0")) };
          default: return { copy: id };
        }
      },
    },
  },
} satisfies Extension;
