// Unicode characters over data.json (generated by build.ts: code point,
// name, section, keywords, HTML entity name): a grid inside, tiles are the
// glyphs, sections are the blocks. Copy the character, paste it, or copy
// its code point, HTML entity or numeric reference. The last few picked
// lead the list in a "Recent" section (the extension's storage).
import { settings, storage, type Action, type Detail, type Extension, type Item } from "@zcag/pal";
import data from "./data.json";

type Row = { cp: number; n: string; s: string; k: string[]; e?: string };
/** `[palettes.unicode]`, default in pal.json. */
type PaletteSettings = { columns: number };

const RECENT_KEY = "recent";
const RECENT_MAX = 12;
const RECENT = "Recent";
/** nf-md-omega, from the bundled Nerd Font. */
const ICON = "\u{f03c9}";
/** Text presentation for a character the platform would draw as a colour emoji (⏏, ⏭, 🖱): the tile stays a glyph; what is copied is the bare character. */
const TEXT = "\uFE0E";

const hex = (cp: number) => cp.toString(16).toUpperCase().padStart(4, "0");
/** `U+2192`. */
export const codePoint = (cp: number) => `U+${hex(cp)}`;
/** `&rarr;` when the entity has a name, else the numeric reference. */
export const entity = (r: Row) => (r.e ? `&${r.e};` : numeric(r.cp));
/** `&#x2192;`. */
export const numeric = (cp: number) => `&#x${hex(cp)};`;
/** `E2 86 92`. */
export const utf8 = (cp: number) => [...new TextEncoder().encode(String.fromCodePoint(cp))].map((b) => b.toString(16).toUpperCase().padStart(2, "0")).join(" ");

const rows = new Map<string, Row>((data as Row[]).map((r) => [hex(r.cp), r]));

/** A space or a format character draws nothing on a tile, so its tile is the open box; the name says which it is. */
const glyph = (r: Row) => { if (r.s === "Spaces") return "␣"; const ch = String.fromCodePoint(r.cp); return /\p{Extended_Pictographic}/u.test(ch) ? ch + TEXT : ch; };

const ACTIONS: Action[] = [
  { id: "copy", title: "Copy character" },
  { id: "paste", title: "Paste" },
  { id: "codepoint", title: "Copy code point", shortcut: "cmd+shift+u" },
  { id: "entity", title: "Copy HTML entity", shortcut: "cmd+shift+e" },
  { id: "numeric", title: "Copy numeric reference", shortcut: "cmd+shift+n" },
];

const item = (r: Row, section: string): Item => ({
  id: hex(r.cp),
  name: r.n,
  subtitle: codePoint(r.cp),
  icon: glyph(r),
  keywords: [codePoint(r.cp), ...r.k],
  section,
});

/** The stored ids that are still in the table, newest first. */
async function recent(): Promise<string[]> {
  const ids = await storage.get<unknown>(RECENT_KEY);
  return Array.isArray(ids) ? ids.filter((id): id is string => typeof id === "string" && rows.has(id)) : [];
}

async function remember(id: string) {
  const ids = [id, ...(await recent()).filter((x) => x !== id)].slice(0, RECENT_MAX);
  await storage.set(RECENT_KEY, ids);
}

/** A rounded box with the glyph large in it, as a data url the detail's markdown can show; a mid grey reads in both themes. */
function glyphImage(r: Row): string {
  const text = glyph(r).replace(/[<>&]/g, (c) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;" })[c]!);
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 72"><rect width="120" height="72" rx="8" fill="#80808026"/><text x="60" y="52" font-size="44" text-anchor="middle" fill="#85869A" font-family="-apple-system, Segoe UI, Noto Sans, sans-serif">${text}</text></svg>`;
  return "data:image/svg+xml," + encodeURIComponent(svg).replace(/[()]/g, (c) => (c === "(" ? "%28" : "%29"));
}

function detail(r: Row): Detail {
  const latex = r.k.find((k) => k.startsWith("\\"));
  const aliases = r.k.filter((k) => !k.startsWith("\\"));
  return {
    markdown: `![${r.n}](${glyphImage(r)})\n\n**${r.n}**`,
    metadata: [
      { label: "Block", value: r.s },
      { label: "Code point", value: codePoint(r.cp) },
      { label: "HTML", value: r.e ? `&${r.e}; ${numeric(r.cp)}` : numeric(r.cp) },
      { label: "UTF-8", value: utf8(r.cp) },
      ...(latex ? [{ label: "LaTeX", value: latex }] : []),
      ...(aliases.length ? [{ label: "Also", tags: aliases.slice(0, 6).map((text) => ({ text })) }] : []),
    ],
  };
}

export default {
  palettes: {
    unicode: {
      title: "Unicode Characters",
      icon: ICON,
      view: "grid",
      placeholder: "Name, entity, LaTeX or code point",
      // Palette meta is read once at load (see emoji).
      columns: settings.palette<PaletteSettings>("unicode").columns,
      actions: ACTIONS,
      list: async () => {
        const used = await recent();
        const top = used.map((id) => item(rows.get(id)!, RECENT));
        const rest = (data as Row[]).filter((r) => !used.includes(hex(r.cp))).map((r) => item(r, r.s));
        return [...top, ...rest];
      },
      pick: async (id, action) => {
        const r = rows.get(id);
        if (!r) return { toast: { title: "Unknown character", message: id, style: "failure" } };
        await remember(id);
        const ch = String.fromCodePoint(r.cp);
        switch (action) {
          case "paste": return { paste: { text: ch } };
          case "codepoint": return { copy: codePoint(r.cp) };
          case "entity": return { copy: entity(r) };
          case "numeric": return { copy: numeric(r.cp) };
          default: return { copy: ch };
        }
      },
      detail: (id) => { const r = rows.get(id); return r ? detail(r) : undefined; },
    },
  },
} satisfies Extension;
