// Colours: a grid of named swatches over data.json (generated by build.ts:
// CSS names, pal's tokens, Tailwind, Material) with hex/rgb/hsl to copy,
// and an input palette that converts what is typed. The maths is color.ts.
// The last few picked lead the grid in a "Recent" section (storage).
import { settings, storage, type Action, type Detail, type Extension, type Item, type Metadata } from "@zcag/pal";
import { BLACK, WHITE, complementary, contrast, lighten, nameOf, nearestName, parse, swatch, toHex, toHslString, toHwb, toOklch, toRgb, wcag, type RGB } from "./color.ts";
import data from "./data.json";

type Row = { id: string; n: string; h: string; s: string };
/** `[palettes.colors]`, default in pal.json. */
type PaletteSettings = { columns: number };

const RECENT_KEY = "recent";
const RECENT_MAX = 12;
const RECENT = "Recent";
const ICON = "#4F46D6";

const rows = new Map<string, Row>((data as Row[]).map((r) => [r.id, r]));
const rgbOf = (r: Row): RGB => parse(r.h)!;

const ACTIONS: Action[] = [
  { id: "hex", title: "Copy hex" },
  { id: "rgb", title: "Copy rgb" },
  { id: "hsl", title: "Copy hsl", shortcut: "cmd+shift+h" },
  { id: "name", title: "Copy name", shortcut: "cmd+shift+n" },
];

/** The name as a class or token: `slate-500`, `red-a200`, `aliceblue`, `tag-blue`. */
const token = (r: Row) => r.id.slice(r.id.indexOf("/") + 1).replace(/^(light|dark)\//, "");

const item = (r: Row, section: string): Item => ({
  id: r.id,
  name: r.n,
  subtitle: r.h,
  icon: { image: swatch(r.h) },
  keywords: [r.h, token(r), r.s.toLowerCase()],
  section,
  actions: ACTIONS,
});

async function recent(): Promise<string[]> {
  const ids = await storage.get<unknown>(RECENT_KEY);
  return Array.isArray(ids) ? ids.filter((id): id is string => typeof id === "string" && rows.has(id)) : [];
}
async function remember(id: string) {
  await storage.set(RECENT_KEY, [id, ...(await recent()).filter((x) => x !== id)].slice(0, RECENT_MAX));
}

const tag = (c: RGB) => ({ text: toHex(c), color: toHex(c) });
const ratio = (c: RGB, on: RGB) => { const r = contrast(c, on); return { r, text: `${r.toFixed(2)}:1`, level: wcag(r) }; };
const LEVEL_COLOR = { AAA: "green", AA: "green", "AA large": "amber", fail: "red" } as const;

/** A wide swatch over the notations, the nearest name, contrast on white and black, and the relatives as coloured tags. */
export function detailOf(c: RGB, title: string): Detail {
  const hex = toHex(c);
  const exact = nameOf(c);
  const near = exact ? undefined : nearestName(c);
  const [w, b] = [ratio(c, WHITE), ratio(c, BLACK)];
  const metadata: Metadata[] = [
    { label: "Hex", value: hex },
    { label: "RGB", value: toRgb(c) },
    { label: "HSL", value: toHslString(c) },
    { label: "HWB", value: toHwb(c) },
    { label: "OKLCH", value: toOklch(c) },
    exact ? { label: "CSS name", value: exact } : { label: "Nearest name", value: near!.name, tags: [{ text: nearestTag(near!.distance), color: "grey" }] },
    { label: "On white", value: w.text, tags: [{ text: w.level, color: LEVEL_COLOR[w.level] }] },
    { label: "On black", value: b.text, tags: [{ text: b.level, color: LEVEL_COLOR[b.level] }] },
    { label: "Complementary", tags: [tag(complementary(c))] },
    { label: "Lighter", tags: [0.1, 0.2, 0.3].map((a) => tag(lighten(c, a))) },
    { label: "Darker", tags: [0.1, 0.2, 0.3].map((a) => tag(lighten(c, -a))) },
  ];
  return { markdown: `![${hex}](${swatchWide(hex)})\n\n**${title}**`, metadata };
}
const nearestTag = (d: number) => (d < 0.02 ? "close" : d < 0.06 ? "near" : "far");
const swatchWide = (hex: string) => `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 48"><rect width="120" height="48" rx="8" fill="${hex}"/></svg>`)}`;

// ---- convert ---------------------------------------------------------------

const hint = (name: string, subtitle: string): Item => ({ id: `hint:${name}`, name, subtitle, icon: ICON, actions: [] });
const HINTS = [
  hint("Type a colour", "#ff8800, rgb(255 136 0), hsl(30 100% 50%), hwb(30 0% 0%), oklch(0.75 0.18 60), or a CSS name"),
  hint("Every row is one notation of it", "Enter copies the row; the detail pane (⌘I) has contrast, the nearest name and relatives"),
];

/** The conversions of `c`, one row each; the row's id is its value, so a pick copies it. */
export function conversions(c: RGB): Item[] {
  const hex = toHex(c);
  const exact = nameOf(c);
  const near = exact ? undefined : nearestName(c);
  const detail = detailOf(c, exact ?? hex);
  const icon = { image: swatch(hex) };
  const copy: Action[] = [{ id: "copy", title: "Copy" }];
  const row = (id: string, name: string, subtitle: string, accessories?: Item["accessories"]): Item => ({ id, name, subtitle, icon, detail, accessories, actions: copy });
  const [w, b] = [ratio(c, WHITE), ratio(c, BLACK)];
  return [
    row(hex, hex, "hex"),
    row(toRgb(c), toRgb(c), "rgb"),
    row(toHslString(c), toHslString(c), "hsl"),
    row(toHwb(c), toHwb(c), "hwb"),
    row(toOklch(c), toOklch(c), "oklch"),
    exact ? row(exact, exact, "CSS name") : row(near!.name, near!.name, `nearest CSS name, ${CSS_HEX(near!.name)}`, [{ tag: nearestTag(near!.distance), color: "grey" }]),
    row(w.text, `${w.text} on white`, "contrast ratio", [{ tag: w.level, color: LEVEL_COLOR[w.level] }]),
    row(b.text, `${b.text} on black`, "contrast ratio", [{ tag: b.level, color: LEVEL_COLOR[b.level] }]),
  ];
}
const CSS_HEX = (name: string) => toHex(parse(name)!);

export default {
  palettes: {
    colors: {
      title: "Colors",
      icon: ICON,
      view: "grid",
      // Palette meta is read once at load (see emoji).
      columns: settings.palette<PaletteSettings>("colors").columns,
      list: async () => {
        const used = await recent();
        return [...used.map((id) => item(rows.get(id)!, RECENT)), ...(data as Row[]).filter((r) => !used.includes(r.id)).map((r) => item(r, r.s))];
      },
      pick: async (id, action) => {
        const r = rows.get(id);
        if (!r) return { toast: { title: "Unknown colour", message: id, style: "failure" } };
        await remember(id);
        const c = rgbOf(r);
        switch (action) {
          case "rgb": return { copy: toRgb(c) };
          case "hsl": return { copy: toHslString(c) };
          case "name": return { copy: token(r) };
          default: return { copy: r.h };
        }
      },
      detail: (id) => { const r = rows.get(id); return r ? detailOf(rgbOf(r), r.n) : undefined; },
    },
    convert: {
      title: "Convert colour",
      icon: ICON,
      input: true,
      placeholder: "#ff8800, rgb(255 136 0), hsl(30 100% 50%), a name",
      list: (query = "") => {
        const q = query.trim();
        if (!q) return HINTS;
        const c = parse(q);
        return c ? conversions(c) : [hint("Not a colour", `${q} is none of hex, rgb(), hsl(), hwb(), oklch() or a CSS name`)];
      },
      pick: (id) => (id.startsWith("hint:") ? { keep: true } : { copy: id }),
    },
  },
} satisfies Extension;
